#!/usr/bin/env fish

function stow_dotfiles
    set file $argv
    if test -d $file -a $file != ".git" -a $file != "addons"
        echo "Installing $file"
        if test (uname) = "Darwin" -a -e $file-mac
            stow $file-mac
        else
            stow $file
        end
    else if test ! -e $file
        echo "Error: $file does not exist"
    end
end

if test -z $argv
    for file in (ls -A)
        if not string match "*-mac" $file > /dev/null
            stow_dotfiles $file
        end
    end
else
    for file in $argv
        stow_dotfiles $file
    end
end

