#!/bin/fish

# Unstow all the dotfiles
if test -z $argv
    for file in (ls -A)
        if test -e $file -a $file != "install" -a $file != "README.md" -a $file != ".git"
            echo "Installing $file"
            stow $file
        else if test ! -e $file
            echo "Error: $file does not exist"
        end
    end
else
    for file in $argv
        if test -e $file -a $file != "install" -a $file != "README.md" -a $file != ".git"
            echo "Installing $file"
            stow $file
        else if test ! -e $file
            echo "Error: $file does not exist"
        end
    end
end
