pcall(require, "impatient")
require("user.options")
require("user.plugins")
require("user.keymaps")
if vim.g.vscode then
    return
end
require("user.autocommands")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.lualine")
require("user.comment")
require("user.todo-comments")
require("user.gitsigns")
require("user.nvim-tree")
require("user.toggleterm")
require("user.dial")
require("user.indent-blankline")
--[[ require("user.bufferline") ]]
require("user.cybu")
require("user.dap")
require("user.neoscroll")
require("user.dressing")
require("user.acr")
require("user.navic")
require("user.colorscheme")
